# Makefile for mesh_d2s_single viewer demo
#
# This code is part of the Diderot Project (http://diderot-language.cs.uchicago.edu)
#
# COPYRIGHT (c) 2015 The University of Chicago
# All rights reserved.
#

TARGET		= ex1

build:	$(TARGET)

include fem/makedefs.gmk
include fem/makerules_so.gmk

override DIDEROTC_FLAGS	+= --namespace=ex1

